"""
Django settings for mcsi project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/dev/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/dev/ref/settings/
"""

import os
import platform

import pymysql

pymysql.install_as_MySQLdb()
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

PROJECT_PATH = os.path.dirname(os.path.dirname(__file__))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/dev/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3t4a6f)g0m!#n-o#^hx%2onuwa0!ndxu%ltnqvdl=mkj9l=(jw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['uhaalag_server/api/nomin_pos/get_info','test.smartenergy.mn','uhaalag_server:8080','uhaalag_server','test-office.smartenergy.mn:8081','test-office.smartenergy.mn/api/nomin_pos/get_info','office.smartenergy.mn','office.smartenergy.mn:8081','test-office.smartenergy.mn','10.0.19.123:8081','10.0.19.123','10.0.16.71','10.0.19.123:8089','localhost','127.0.0.1', '10.0.1.10', '66.181.175.36', '192.168.223.14', '192.168.223.16', '122.201.28.55', '122.201.28.56', 'ad.e-s.mn', 'e-s.mn', 'www.e-s.mn']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'highcharts',
    'apps.homepage',
    'apps.data',
    'mathfilters',
    'apps.api',
    'rest_framework',
    #'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',    
    #'debug_toolbar.middleware.DebugToolbarMiddleware',
    # 'session_security.middleware.SessionSecurityMiddleware',
    # 'apps.homepage.middleware.SessionIdleTimeout'
]

REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework_xml.parsers.XMLParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_xml.renderers.XMLRenderer'        
    ],    
    
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 10
}

AUTO_LOGOUT_DELAY = 60*60

EXPIRE_AFTER=60
WARN_AFTER = 30

# SESSION_SECURITY_EXPIRE_AFTER=60*30
# SESSION_SECURITY_WARN_AFTER=5
# SESSION_EXPIRE_AT_BROWSER_CLOSE=True

ROOT_URLCONF = 'mcsi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_PATH + '/templates/',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mcsi.wsgi.application'

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

# Database
# https://docs.djangoproject.com/en/dev/ref/settings/#databases

if 'Windows' in platform.system():
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'uhaa_erchim',
            'USER': 'root',
            'PASSWORD': 'Soft2015',
            'HOST': '10.0.19.123',
            'PORT': '3306',
        },
        'portal': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'uhaa_portal',
            'USER': 'root',
            'PASSWORD': 'Soft2015',
            'HOST': '10.0.19.123',
            'PORT': '3306',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'uhaa_erchim',
            'USER': 'root',
            'PASSWORD': 'Soft2015',
            'HOST': '10.0.19.123',
            'PORT': '3306',
        },
        'portal': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'uhaa_portal',
            'USER': 'root',
            'PASSWORD': 'Soft2015',
            'HOST': '10.0.19.123',
            'PORT': '3306',
        }
    }

# EMAIL_HOST = 'smtp.smartenergy.mn'
EMAIL_HOST = 'us2.smtp.mailhostbox.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'info@smartenergy.mn'
EMAIL_HOST_PASSWORD = 'xR%YGSz9'
EMAIL_USE_TLS = True
# EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = 'info@smartenergy.mn'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
SERVER_EMAIL = 'info@smartenergy.mn'

# Password validation
# https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_PROFILE_MODULE = 'data.UserProfile'


# Internationalization
# https://docs.djangoproject.com/en/dev/topics/i18n/

LANGUAGE_CODE = 'mn-mn'

TIME_ZONE = 'Asia/Ulaanbaatar'

USE_I18N = True

USE_L10N = False

USE_TZ = False

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/dev/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIR = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = PROJECT_PATH + "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

DATA_UPLOAD_MAX_NUMBER_FIELDS = 9999
