# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 15:05
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180514_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHasBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('bank_code', models.CharField(max_length=100, null=True)),
                ('bank_id', models.IntegerField(null=True)),
                ('customer_id', models.IntegerField(null=True)),
                ('created_user_id', models.IntegerField(null=True)),
                ('updated_user_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'data_customer_has_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(choices=[('0', 'Идэвхигүй'), ('1', 'Идэвхитэй')], default='1', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('dans', models.CharField(max_length=255, null=True)),
                ('account_id', models.CharField(max_length=255, null=True)),
                ('created_user_id', models.IntegerField(null=True)),
                ('updated_user_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'data_bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('order_no', models.CharField(max_length=50, null=True)),
                ('invoice_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.IntegerField(default=0, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('customer_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'data_payment_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=80, null=True)),
                ('request_date', models.DateTimeField(null=True)),
                ('request', models.TextField(null=True)),
                ('response_date', models.DateTimeField(null=True)),
                ('response', models.TextField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('bank_type', models.CharField(max_length=50, null=True)),
                ('error', models.TextField(null=True)),
            ],
            options={
                'db_table': 'data_service_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaslaltZalgalt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_user_id', models.CharField(max_length=250)),
                ('is_active', models.CharField(choices=[('0', 'Идэвхигүй'), ('1', 'Идэвхитэй')], default='1', max_length=50)),
                ('code', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-created_date',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='avlaga',
            name='is_discount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avlaga',
            name='payment_gap',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='avlaga',
            name='prev_year_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, null=True),
        ),
    ]
